Lint fixes.

diff --git a/bin/decrypt b/bin/decrypt
--- a/bin/decrypt
+++ b/bin/decrypt
@@ -38,7 +38,7 @@ init() {
     declare -gi unpack=1
     declare -gi quiet=0
 
-    while (( ${#} > 0 )); do
+    while (( $# > 0 )); do
         case "${1}" in
             --) ;;
             -i|--identity) shift; assertFile "${1}"; identities+=(-i "${1}") ;;
@@ -55,13 +55,13 @@ init() {
         shift
     done
 
-    [[ ${#identities[@]} ]] || fail "no identities specified"
-    [[ ${file} ]] || fail "no file provided"
-    [[ ${decryptedFile} ]] || decryptedFile="${ basename -- "${file}" .${ageFileExtension}; }"
+    [[ -n ${#identities[@]} ]] || fail "no identities specified"
+    [[ -n ${file} ]] || fail "no file provided"
+    [[ -n ${decryptedFile} ]] || decryptedFile="${ basename -- "${file}" .${ageFileExtension}; }"
 }
 
 setFile() {
-    [[ ${file} ]] && usage "PATH can only be specified once"
+    [[ -n ${file} ]] && usage "PATH can only be specified once"
     file="${1}"
     [[ -e ${file} ]] || fail "${file} not found"
     [[ -f ${file} ]] || fail "${file} is not a file"
@@ -89,7 +89,7 @@ unpackFile() {
 }
 
 setUnpackDir() {
-    if [[ ! ${unpackDir} ]]; then
+    if [[ -z ${unpackDir} ]]; then
         unpackDir="${ echo "${decryptedFile}" | cut -d'.' -f1; }-content"
     fi
     [[ -e ${unpackDir} ]] && replaceOutputFile "${unpackDir}"
diff --git a/bin/encrypt b/bin/encrypt
--- a/bin/encrypt
+++ b/bin/encrypt
@@ -51,7 +51,7 @@ init() {
     outputFile=    # the generated output file path.
     isArchive=     # if output file is an archive
 
-    while (( ${#} > 0 )); do
+    while (( $# > 0 )); do
         case "${1}" in
             --) ;;
             -r|--recipient) shift; assertRecipient "${1}"; recipients+=(-r "${1}") ;;
@@ -70,8 +70,8 @@ init() {
         shift
     done
 
-    [[ ${#recipients[@]} ]] || fail "no recipients specified"
-    [[ ${verifyKeyFile} ]] || deleteOriginal=0
+    [[ -n ${#recipients[@]} ]] || fail "no recipients specified"
+    [[ -n ${verifyKeyFile} ]] || deleteOriginal=0
     initializeFiles
 }
 
@@ -93,12 +93,12 @@ initializeFiles() {
     (( ${inputCount} == 0 )) && usage "no files provided"
     if (( ${#files[@]} == 1 )) && [[ -f ${files[0]} ]]; then
         inputFile="${files[0]}"
-        [[ ${name} ]] || name="${ basename ${inputFile}; }"
+        [[ -n ${name} ]] || name="${ basename ${inputFile}; }"
         description="${name} file"
         extension="${ageFileExtension}"
         unset isArchive
     else
-        [[ ${name} ]] || name="vault"
+        [[ -n ${name} ]] || name="vault"
         description="${name}"
         inputFile="${ tempDirPath ${name}.${tarFileExtension}; }"
         extension="${tarFileExtension}.${ageFileExtension}"
@@ -106,7 +106,7 @@ initializeFiles() {
         tar -Jcf "${inputFile}" "${files[@]}" || fail
         isArchive='yes'
     fi
-    if [[ ${name} ]]; then
+    if [[ -n ${name} ]]; then
         baseName="${name}"
     else
         baseName="${ basename "${inputFile}" | cut -d. -f1; }"
@@ -131,13 +131,13 @@ encryptFile() {
 }
 
 verifyEncryptedFile() {
-    if [[ ${verifyKeyFile} ]]; then
-        local decryptedFile="${ tempDirPath file; }"
-        local verifyDir="${ tempDirPath file-content; }"
+    if [[ -n ${verifyKeyFile} ]]; then
+        local decryptedFile; decryptedFile=${ tempDirPath file; }
+        local verifyDir; verifyDir=${ tempDirPath file-content; }
         show "Verifying" cyan "${outputFile}"
         valt ../bin/decrypt -i "${verifyKeyFile}" ${outputFile} -o "${decryptedFile}" -u "${verifyDir}" -f -q || fail
 
-        if [[ ${isArchive} ]]; then
+        if [[ -n ${isArchive} ]]; then
             local file i
             for (( i=0; i < ${inputCount}; i++ )); do
                 file="${files[${i}]}"
