Switch to using html instead of markdown for key document template.

diff --git a/etc/keys b/etc/keys
--- a/etc/keys
+++ b/etc/keys
@@ -2,22 +2,25 @@
 
 usage() {
     echo
-    echo "$(ansi bold Generate an age public key pair and optional documentation)."
+    echo "$(ansi bold Generate an age public key pair and backup documentation)."
     echo
-    echo "Usage: $(ansi bold_blue sage ${scriptName}) [OPTIONS] [NAME]"
+    echo "Usage: $(ansi bold_blue valt keys ${scriptName}) [OPTIONS] [NAME]"
     echo
-    echo "If no name is specified it defaults to 'age'."
+    echo "If no name is specified it defaults to 'my'."
     echo
-    echo "Private keys are encrypted and strong passphrases are $(ansi bold_green highly) encouraged; advice and an opportunity to"
+    echo "Private keys are encrypted and a strong passphrase is $(ansi bold_green highly) encouraged; advice and an opportunity to"
     echo "generate one will be offered."
     echo
-    echo "A customized PDF file can be generated containing your keys, in encrypted form, to serve as a backup for you and/or your"
+    echo "A PDF file will be created containing your keys, also in encrypted form, to serve as a backup for you and/or your"
     echo "successors. Keys are represented as a QR code and again in a text format — when printed, such representations are often"
-    echo "called \"paper keys\". Detailed usage instructions are included, personalized with information (e.g. emergency contacts)"
-    echo "that you supply in a separate file."
+    echo "called \"paper keys\". Detailed usage instructions are included and should be personalized with information (e.g. emergency contacts)"
+    echo "that you supply in a separate file via the --document option. When not specified, an example file will be used."
     echo
-    echo "Use of the paper key $(ansi italic will require) the encryption passphrase. Space is provided for you to record it by hand, but this"
-    echo "should only be done when the documents is stored is a secure location such as a safe deposit box of fire safe."
+    echo "Space is provided in the document for you to record your passphrase by hand. Please do so, and then:"
+    echo
+    echo "      $(ansi bold store the document in a secure location such as a safe deposit box or fire safe!)"
+    echo
+    echo "Better, store copies in multiple secure places, perhaps also with a trusted friend or family member."
     echo
     echo "Options"
     echo
@@ -25,12 +28,12 @@ usage() {
     echo "    --no-verify                   Do not verify keys."
     echo "    --no-advice                   Do not show passphrase advice."
     echo "    -q, --quick                   Do not verify keys or show passphrase advice."
-    echo "    -d, --document SUBSTITUTIONS  Generate a PDF using the SUBSTITUTIONS file. Try it using the example file below."
+    echo "    -d, --document SUBSTITUTIONS  Use the SUBSTITUTIONS file when generating the document."
     echo "    -t, --template TEMPLATE       Use the TEMPLATE markdown file instead of the default for PDF generation."
     echo "    -c, --css CSS                 Apply style overrides from the CSS file for PDF generation."
     echo "    -h, --help                    Display usage and exit."
     echo
-    echo "Paper Key Customization"
+    echo "Document Customization"
     echo
     echo "Substitutions are performed with simple key/value pairs defined in a file such as:"
     echo
@@ -46,17 +49,14 @@ usage() {
     echo
     echo "    ${cssMainFile}"
     echo
-    bye "${@}"
+    bye
 }
 
 main() {
     init "${@}"
     createKeys
     if [[ ${substitutionsFile} ]]; then
-        prepareMarkdown
-        if [[ ${document} ]]; then
-            createDocument
-        fi
+        createDocument
     fi
     echo
 }
@@ -64,53 +64,56 @@ main() {
 init() {
     readonly scriptName=$(basename "${0}")
     readonly exampleSubstitutionsFile="${VALT_ETC_DIR}/key-doc-example-substitutions.sh"
-    readonly cssMainFile="${VALT_ETC_DIR}/key-doc.css"
-    readonly logoFile="${VALT_ETC_DIR}/phoggy.png"
-    readonly markdownFileName='note.md'
-    readonly qrFileName='qr.png'
+    readonly cssMainFileName="key-doc.css"
+    readonly cssOverrideFileName='override.css'
+    readonly logoFileName="phoggy.png"
+    readonly htmlFileName='note.html'
+    readonly qrCodeFileName='qr.png'
+    readonly cssMainFile="${VALT_ETC_DIR}/${cssMainFileName}"
+    readonly logoFile="${VALT_ETC_DIR}/${logoFileName}"
 
-    templateFile="${VALT_ETC_DIR}/key-doc-template.md"
+    templateFile="${VALT_ETC_DIR}/key-doc-template.html"
+    substitutionsFile="${exampleSubstitutionsFile}"
     cssOverrideFile=
-    substitutionsFile=
-    tempMarkdownFile=
-
-    prefix=
-    document=
-    force=
-    tempMarkdownFile=
-    tempQRFile=
+    htmlFile=
+    prefix="${USER}"
+    htmlFile=
+    qrCodeFile=
     armoredKey=
-    showKeyAdvice=yes
-    verifyKeys=yes
+
+    # Flags
+    declare -i force=0
+    declare -i showKeyAdvice=1
+    declare -i verifyKeys=1
 
     while ((${#} > 0)); do
         case "${1}" in
             -d | --document) shift; setSubstitutionsFile "${1}" ;;
             -t | --template) shift; setFileVar templateFile "${1}" "TEMPLATE" ;;
             -c | --css) shift; setFileVar cssOverrideFile "${1}" "CSS" ;;
-            --no-verify) unset verifyKeys ;;
-            --no-advice) unset showKeyAdvice ;;
-            -q | --quick) unset showKeyAdvice verifyKeys ;;
-            -f | --force) force=yes ;;
+            --no-verify) verifyKeys=0 ;;
+            --no-advice) showKeyAdvice=0 ;;
+            -q | --quick) showKeyAdvice=0; verifyKeys=0 ;;
+            -f | --force) force=1 ;;
             -h | --help) usage ;;
-            --version) version "${VERSION}" ;;
             *) setPrefix "${1}" ;;
-            esac
+        esac
         shift
     done
 
-    [[ ${prefix} ]] || prefix='my'
-    privateKeyFile="${prefix}-age.key"
-    publicKeyFile="${prefix}-public-age.key"
+    privateKeyFile="${prefix}.key"
+    publicKeyFile="${prefix}-public.key"
     documentsFile="${prefix}-key.pdf"
 
-    [[ ${force} ]] || assertFileDoesNotExist "${privateKeyFile}"
-    [[ ${force} ]] || assertFileDoesNotExist "${publicKeyFile}"
+    (( force )) || {
+        assertFileDoesNotExist "${privateKeyFile}"
+        assertFileDoesNotExist "${publicKeyFile}"
+    }
     rm "${publicKeyFile}" "${privateKeyFile}" 2> /dev/null
 }
 
 setPrefix() {
-    [[ ${prefix} ]] && usage "name can only be specified once"
+    assertValidFileName "${1}"
     prefix="${1}"
 }
 
@@ -119,14 +122,12 @@ setSubstitutionsFile() {
     [[ ${file} == 'example' ]] && file="${exampleSubstitutionsFile}"
     setFileVar substitutionsFile "${file}" "SUBSTITUTIONS"
     [[ ${force} ]] || assertFileDoesNotExist "${documentsFile}"
-    require 'rayvn/pdf'
-    require 'rayvn/readpass'
 }
 
 createKeys() {
     echo
     echo "$(ansi bold Generating keys)"
-    if [[ ${showKeyAdvice} ]]; then
+    if (( showKeyAdvice )); then
         echo
         showAgeKeyPairAdvice
         local reply
@@ -139,7 +140,7 @@ createKeys() {
     echo "Public key (aka 'recipient') file: $(ansi cyan ${publicKeyFile})"
     echo "Private key (aka 'identity') file: $(ansi cyan ${privateKeyFile}) (also contains public key)"
 
-    if [[ ${verifyKeys} ]]; then
+    if (( verifyKeys )); then
         echo
         echo "$(ansi bold Verifying keys)"
         echo
@@ -154,96 +155,140 @@ generatePass() {
     echo
 }
 
-prepareMarkdown() {
-    tempMarkdownFile=$(tempDirPath ${markdownFileName})
-
-    armorAgeFile "${privateKeyFile}" armoredKey
-
-    tempQRFile=$(tempDirPath ${qrFileName})
-    createCRCode || fail
-    assertFileExists "${tempQRFile}"
-
-    author=$(generateMarkdown "${templateFile}" "${substitutionsFile}" "${tempMarkdownFile}") || fail
-    assertFileExists "${tempMarkdownFile}"
-
-    document=yes
-}
-
-generateMarkdown() {
-    local templateFile="${1}"
-    local substitutionsFile="${2}"
-    local outputFile="${3}"
-
-    sourceEnvFile "${substitutionsFile}"
-
-    # set built-n substitutions
-    local _LOGO_PATH="${logoFile}"
-    local _DATE="$(date "+%B %d, %Y %r %Z")"
-    local _QR_CODE="![QR code](${tempQRFile})"
-    local _ARMORED_KEY="${armoredKey}"
-
-    local markdown="$(cat ${templateFile})"
-    local substitutionsSource="${markdown}"
-    local substitutionsFile=()
-    while [[ ${substitutionsSource} =~ ([^{]*)\}(.*) ]]; do
-        substitutionsFile+=("${BASH_REMATCH[1]}")
-        substitutionsSource="${BASH_REMATCH[2]}"
-    done
-    for key in "${substitutionsFile[@]}"; do
-        [[ -v "${key}" ]] || fail "${key} not set in ${substitutionsFile}"
-        local value="${!key}"
-        if [[ ${key} == 'CONTACTS' ]]; then
-            # transform the ';' separated contacts into a markdown list
-            value=
-            local contacts contact
-            IFS=';' read -r -a contacts <<<"${CONTACTS}"
-            for contact in "${contacts[@]}"; do
-                value+="${newline}- ${contact#"${contact%%[![:space:]]*}"}"
-            done
-        fi
-        markdown=${markdown/\{${key}\}/${value}}
-    done
-    echo "${markdown}" >${outputFile}
-    # echo "${markdown}" > temp.md # TODO REMOVE!
-    echo "${AUTHOR}"
-}
-
-createCRCode() {
-    echo "${armoredKey}" | qrencode -l H -o "${tempQRFile}"
-}
-
 createDocument() {
+    local options=
     echo
     echo "$(ansi bold Generating documentation)"
     echo
-    local options="--css ${cssMainFile}"
-    [[ ${cssOverrideFile} ]] && options+=" --css ${cssOverrideFile}"
+    generatePdf
+    echo
+    echo "Keys documented in $(ansi cyan ${documentsFile})"
+    open "${documentsFile}" &> /dev/null
+}
 
-    # Options, see https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
-    # TODO: add footer with page numbers, date and valt version
-    ## options+=" --pdf-engine-opt=--enable-local-file-access"
-    #    options+=" --pdf-engine-opt=--footer-font-name --pdf-engine-opt=arial"
-    #    options+=" --pdf-engine-opt=--footer-font-size --pdf-engine-opt=10"
-    #    options+=" --pdf-engine-opt=--footer-left --pdf-engine-opt=[date]"
-    #    options+=" --pdf-engine-opt=--footer-right --pdf-engine-opt=[page]/[topage]"
-    #    # options+=" --pdf-engine-opt=--footer-html --pdf-engine-opt=./footer.html"
+# TODO: --+----+-++(-++(---++++(---+(((+)))+---)++++---)++-)++-+-----+--
 
-    #    pandoc -f gfm -t html5 ${options} "${tempMarkdownFile}" -o "${documentsFile}" || fail
-    pandoc -f gfm -t html5 --metadata pagetitle="x" ${options} "${tempMarkdownFile}" -o "${documentsFile}" || fail
+generatePdf() {
+    local workDir=$(tempDirPath)
+
+    # Set armoredKey var
+
+    armorAgeFile "${privateKeyFile}" armoredKey
+
+    # Copy required files
+
+    cp "${cssMainFile}" "${workDir}/${cssMainFileName}" || fail
+    cp "${logoFile}" "${workDir}/${logoFileName}" || fail
+    if [[ ${cssOverrideFile} ]]; then
+        cp "${cssOverrideFile}" "${workDir}/${cssOverrideFileName}" || fail
+    fi
+
+    # Create QR code
+
+    qrCodeFile="${workDir}/${qrCodeFileName}"
+    echo "${armoredKey}" | qrencode -l H -o "${qrCodeFile}" || fail
+    assertFileExists "${qrCodeFile}"
+
+    # Generate substituted html file
+
+    htmlFile="${workDir}/${htmlFileName}"
+    author="$(generateHtml "${htmlFile}")"
+    assertFileExists "${htmlFile}"
+
+    # Move to work dir
+
+    cd ${workDir} || fail
+
+    # Convert html to pdf
+
+    wkhtmltopdf --enable-local-file-access \
+                --footer-left "${author} Private Key" \
+                --footer-center "$(date '+%B %e, %Y')" \
+                --footer-right "Page [page] of [topage]" \
+                --footer-font-name "Helvetica, Arial, sans-serif" \
+                --footer-font-size 8 \
+                --margin-bottom 15mm \
+                "${htmlFile}" "${documentsFile}"
 
     # Set metadata and encrypt with a strong password
 
-    local ownerPW="$(generatePassword)"
-    local userPW='' # or else will have to enter to view!
-    cpdf -set-title "Public/Private Key Pair Backup" "${documentsFile}" -o "${documentsFile}" 2>/dev/null || fail
-    cpdf -set-author "${author}" "${documentsFile}" -o "${documentsFile}" 2>/dev/null || fail
-    cpdf -set-creator "${VALT_VERSION}, ${VALT_PROJECT_URL}" "${documentsFile}" -o "${documentsFile}" 2>/dev/null || fail
-    cpdf -set-subject "${prefix} keys" "${documentsFile}" -o "${documentsFile}" 2>/dev/null || fail
-    cpdf -encrypt AES256 "${ownerPW}" "${userPW}" -no-edit -no-encrypt-metadata "${documentsFile}" -o "${documentsFile}" 2>/dev/null || fail
-    echo
-    echo "Keys documented in $(ansi cyan ${documentsFile})"
+    local valtProjectUrl='https://github.com/phoggy/valt'
+    local title='Private Key Pair Backup & Usage Instructions'
+    local creator="$(projectVersion valt), ${valtProjectUrl}"
+    local subject="File decryption."
+    local keywords="${author}, valt, private key, backup, encryption, decryption, security"
+    local ownerPW="$(phraze)" # TODO: use private key pass so owner could modify this doc??
+    local userPW='' # must be empty or else will have to enter to view!
+
+    cpdf -set-title "${title}" ${documentsFile} AND \
+         -set-author "${author}" AND \
+         -set-creator "${creator}" AND \
+         -set-subject "${subject}" AND \
+         -set-keywords "${keywords}" AND \
+         -no-edit AND \
+         -no-encrypt-metadata AND \
+         -encrypt AES256 "${ownerPW}" "${userPW}" \
+         -o "${documentsFile}" || fail
 }
 
-source rayvn.up 'rayvn/core' 'rayvn/age' 'rayvn/safe-env'
+generateHtml() {
+    local outputFile="${1}"
+    local html="$(< ${templateFile})" || fail
+    local contact value
+
+    # Set user provided substitutions
+
+    sourceSafeStaticVars "${substitutionsFile}"
+
+    # Set built-in substitution values(clobbering any that the user might have defined)
+
+    local _DATE="$(date "+%B %d, %Y %r %Z")"
+    local _CSS_PATH="${cssMainFileName}"
+    local _LOGO_PATH="${logoFileName}"
+    local _QR_CODE_PATH="${qrCodeFileName}"
+    local _ARMORED_KEY="${armoredKey}"
+    local _CONTACTS_LIST= # transformed later
+    local _CSS_OVERRIDE='<!-- placeholder -->'
+    if [[ ${cssOverrideFile} ]]; then
+        _CSS_OVERRIDE="<link rel="stylesheet" href="${cssOverrideFileName}">"
+    fi
+
+    # Collect all required substitution keys (consumes tempHtml)
+
+    local tempHtml="${html}"
+    local requiredSubstitutionKeys=()
+
+    while [[ ${tempHtml} =~ ([^{]*)\}(.*) ]]; do
+        requiredSubstitutionKeys+=("${BASH_REMATCH[1]}")
+        tempHtml="${BASH_REMATCH[2]}"
+    done
+
+    # Insist on an 'author' var in template
+
+    [[ "${author}" ]] || fail "'${author}' is required in ${templateFile}"
+
+    # Perform the substitutions, failing if a required substitution is not defined
+
+    for key in "${requiredSubstitutionKeys[@]}"; do
+        value="${!key}"
+        [[ -v "${key}" ]] || fail "${key} not set in ${substitutionsFile}"
+
+        # Special case contacts and transform into list items
+
+        if [[ ${key} == '_CONTACTS_LIST' ]]; then
+            value=
+            for contact in "${contacts[@]}"; do
+                value+="<li>${contact}</li>"
+            done
+        fi
+        [[ "${value}" ]] || fail "${key} value not set in ${substitutionsFile}"
+        html=${html/\$\{${key}\}/${value}}
+    done
+    echo "${html}" > "${outputFile}"
+
+    echo "${author}"
+}
+
+source rayvn.up --add valt 'rayvn/core' 'rayvn/age' 'rayvn/safe-env' 'rayvn/pdf' 'rayvn/readpass'
 
 main "${@}"
